package UI;

import Entidades.Cliente;
import Entidades.Producto;
import Entidades.DetalleVenta;
import Mocks.ProductosDAOMock;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class CompradorMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CompradorMain.class.getName());
    private Cliente cliente;
    private List<DetalleVenta> carrito = new ArrayList<>();
    private ProductosDAOMock productosDAO = new ProductosDAOMock();
    
    
    public CompradorMain(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        lblWelcome.setText("Bienvenido " + cliente.getNombre());
        cargarProductosTabla();
        actualizarTotal();
        setLocationRelativeTo(null);
    }
    private void cargarProductosTabla() {
        List<Producto> lista = productosDAO.obtenerProductosPorNombre("");
        DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
        model.setRowCount(0);
        for (Producto p : lista) {
            model.addRow(new Object[]{p.getId(), p.getNombre(), p.getPrecio(), p.getStock()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnAgregarCarrito = new javax.swing.JButton();
        btnVerCarrito = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 102, 102));
        lblWelcome.setText("Bienvenido al Minimarket ");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        btnAgregarCarrito.setBackground(new java.awt.Color(0, 0, 0));
        btnAgregarCarrito.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnAgregarCarrito.setForeground(new java.awt.Color(0, 255, 204));
        btnAgregarCarrito.setText("Agregar al Carrito");
        btnAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarritoActionPerformed(evt);
            }
        });

        btnVerCarrito.setBackground(new java.awt.Color(0, 0, 0));
        btnVerCarrito.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnVerCarrito.setForeground(new java.awt.Color(0, 255, 204));
        btnVerCarrito.setText("Ver Carrito");
        btnVerCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCarritoActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblTotal.setText("Total");

        btnComprar.setBackground(new java.awt.Color(0, 0, 0));
        btnComprar.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(0, 255, 204));
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarCarrito)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerCarrito)
                                .addGap(18, 18, 18)
                                .addComponent(btnComprar)
                                .addGap(42, 42, 42)
                                .addComponent(lblTotal))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCarrito)
                    .addComponent(btnVerCarrito)
                    .addComponent(btnComprar)
                    .addComponent(lblTotal))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarritoActionPerformed
         int fila = tablaProductos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto primero.");
            return;
        }
        int idProd = (int) tablaProductos.getValueAt(fila, 0);
        Producto p = productosDAO.obtenerProductoPorID(idProd);
        String cantidadStr = JOptionPane.showInputDialog(this, "Cantidad a agregar:");
        if (cantidadStr == null) return; // cancel
        int cantidad;
        try {
            cantidad = Integer.parseInt(cantidadStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida.");
            return;
        }
        if (cantidad <= 0 || cantidad > p.getStock()) {
            JOptionPane.showMessageDialog(this, "Cantidad no disponible.");
            return;
        }
        // Crear DetalleVenta (usa constructor con precio actual)
        DetalleVenta detalle = new DetalleVenta(p, cantidad);
        carrito.add(detalle);
        JOptionPane.showMessageDialog(this, "Producto agregado al carrito.");
        actualizarTotal();
    }

    private void actualizarTotal() {
        double total = 0.0;
        for (DetalleVenta d : carrito) total += d.getTotalDetalleVenta();
        lblTotal.setText("Total: S/ " + String.format("%.2f", total));
    }//GEN-LAST:event_btnAgregarCarritoActionPerformed

    private void btnVerCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCarritoActionPerformed
        if (carrito.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío.");
            return;
        }
        StringBuilder sb = new StringBuilder();
        for (DetalleVenta d : carrito) {
            sb.append(d.toString()).append("\n");
        }
        sb.append("\n").append(lblTotal.getText());
        JOptionPane.showMessageDialog(this, sb.toString(), "Carrito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerCarritoActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        if (carrito.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Carrito vacío.");
            return;
        }

        // Aquí llamamos a VentasServicio para generar venta real.
        // Como aún no tienes IVentasDAO sqlite implementado, construimos con mocks:
        // VentasServicio ventasServicio = new VentasServicio(new VentasDAOMock(), new DetalleVentaServicio(), productosDAO);
        // Venta venta = ventasServicio.generarVenta(carrito, cliente.getId());
        // JOptionPane.showMessageDialog(this, "Compra registrada. ID venta: " + venta.getID());

        // Para ahora (probar): solo simular y limpiar carrito:
        JOptionPane.showMessageDialog(this, "Compra simulada. Total = " + lblTotal.getText());
        carrito.clear();
        actualizarTotal();
        cargarProductosTabla(); // si quieres actualizar stocks si usas DAO real
    
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        // 🔹 Crear un cliente de prueba (solo para ejecutar esta ventana directamente)
        Entidades.Cliente clienteDemo = new Cliente("Cliente", "Demo", "demo@gmail.com", "1234", "999999999");
        new CompradorMain(clienteDemo).setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCarrito;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnVerCarrito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
